CREATE TABLE CATEGORY(
  uuid VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  catalog_uuid VARCHAR(36) NOT NULL REFERENCES SHOP_CATALOG(uuid),
  main_supercategory_uuid VARCHAR(36) REFERENCES CATEGORY(uuid)
);

CREATE TABLE CATEGORIES_SUPERCATEGORIES_LINK(
  category_uuid VARCHAR(36) NOT NULL REFERENCES CATEGORY(uuid),
  supercategory_uuid VARCHAR(36) NOT NULL REFERENCES CATEGORY(uuid)
);

CREATE TABLE CATEGORIES_SUBCATEGORIES_LINK(
  category_uuid VARCHAR(36) NOT NULL REFERENCES CATEGORY(uuid),
  subcategory_uuid VARCHAR(36) NOT NULL REFERENCES CATEGORY(uuid)
);