CREATE TABLE PRODUCT(
  uuid VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  main_unit_uuid VARCHAR(36) NOT NULL REFERENCES UNIT(uuid),
  main_category_uuid VARCHAR(36) NOT NULL REFERENCES CATEGORY(uuid),
  catalog_uuid VARCHAR(36) NOT NULL REFERENCES SHOP_CATALOG(uuid)
);

CREATE TABLE PRODUCTS_UNITS_LINK(
  product_uuid VARCHAR(36) NOT NULL REFERENCES PRODUCT(uuid),
  unit_uuid VARCHAR(36) NOT NULL REFERENCES UNIT(uuid)
);

CREATE TABLE PRODUCTS_CATEGORIES_LINK(
  product_uuid VARCHAR(36) NOT NULL REFERENCES PRODUCT(uuid),
  category_uuid VARCHAR(36) NOT NULL REFERENCES CATEGORY(uuid)
);


