CREATE TABLE USERS(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  email CHARACTER VARYING(255),
  password CHARACTER VARYING(255),
  user_type CHARACTER VARYING(255)
);

CREATE TABLE ROLES(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL
);

CREATE TABLE EMPLOYEE_ROLE_LINK(
  employee_uuid CHARACTER VARYING(36) NOT NULL REFERENCES USERS(uuid),
  role_uuid CHARACTER VARYING(36) NOT NULL REFERENCES ROLES(uuid)
);
