CREATE TABLE SHOP_CATALOG(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL
);

CREATE TABLE BIG_STRING (
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  catalog_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SHOP_CATALOG(uuid),
  value TEXT NOT NULL
);

INSERT INTO SHOP_CATALOG(uuid, name, code, creationtime, modificationtime) VALUES (
  '4a9b636e-f065-11e6-9dac-836adef2f3a6', 'Master catalog', 'master_catalog', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);