CREATE TABLE TASKS(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  query CHARACTER VARYING(2500),
  enabled BOOLEAN,
  status CHARACTER VARYING(255) NOT NULL,
  taskRunBeanName CHARACTER VARYING(255) NOT NULL,
  laststarttime TIMESTAMP,
  lastfinishtime TIMESTAMP,
  indexEntityName CHARACTER VARYING(255),
  task_type CHARACTER VARYING(255) NOT NULL
);

CREATE UNIQUE INDEX TASKS_UUID_IDX ON TASKS(uuid);
CREATE UNIQUE INDEX TASKS_CODE_IDX ON TASKS(code);
CREATE INDEX TASKS_NAME_IDX ON TASKS(name);
