CREATE TABLE PRICES(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  catalog_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SHOP_CATALOGS(uuid) ON DELETE RESTRICT,
  unit_uuid CHARACTER VARYING(36) REFERENCES UNITS(uuid) NOT NULL,
  product_uuid CHARACTER VARYING(36) REFERENCES PRODUCTS(uuid) NOT NULL,
  currency_uuid CHARACTER VARYING(36) REFERENCES CURRENCIES(uuid) NOT NULL,
  priceValue REAL NOT NULL
);

CREATE UNIQUE INDEX PRICE_UUID_IDX ON PRICES(uuid);
CREATE INDEX PRICE_CODE_IDX ON PRICES(code);
CREATE INDEX PRICE_NAME_IDX ON PRICES(name);