CREATE TABLE CATEGORIES(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  catalog_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SHOP_CATALOGS(uuid) ON DELETE RESTRICT,
  main_supercategory_uuid CHARACTER VARYING(36) REFERENCES CATEGORIES(uuid) ON DELETE SET NULL,
  description_uuid CHARACTER VARYING(36) REFERENCES BIG_STRINGS(uuid) ON DELETE SET NULL
);

CREATE UNIQUE INDEX CATEGORY_UUID_IDX ON CATEGORIES(uuid);
CREATE INDEX CATEGORY_CODE_IDX ON CATEGORIES(code);
CREATE INDEX CATEGORY_NAME_IDX ON CATEGORIES(name);

CREATE TABLE CATEGORIES_SUPERCATEGORIES_LINKS(
  category_uuid CHARACTER VARYING(36) NOT NULL REFERENCES CATEGORIES(uuid),
  supercategory_uuid CHARACTER VARYING(36) NOT NULL REFERENCES CATEGORIES(uuid)
);