CREATE TABLE PRODUCT(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  shortName CHARACTER VARYING(255),
  main_unit_uuid CHARACTER VARYING(36) REFERENCES UNIT(uuid) ON DELETE SET NULL,
  main_category_uuid CHARACTER VARYING(36) REFERENCES CATEGORY(uuid) ON DELETE SET NULL,
  catalog_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SHOP_CATALOG(uuid) ON DELETE RESTRICT,
  description_uuid CHARACTER VARYING(36) REFERENCES BIG_STRING(uuid) ON DELETE SET NULL
);

CREATE UNIQUE INDEX PRODUCT_UUID_IDX ON PRODUCT(uuid);
CREATE INDEX PRODUCT_CODE_IDX ON PRODUCT(code);
CREATE INDEX PRODUCT_NAME_IDX ON PRODUCT(name);

CREATE TABLE PRODUCTS_UNITS_LINK(
  product_uuid CHARACTER VARYING(36) NOT NULL REFERENCES PRODUCT(uuid),
  unit_uuid CHARACTER VARYING(36) NOT NULL REFERENCES UNIT(uuid)
);

CREATE TABLE PRODUCTS_CATEGORIES_LINK(
  product_uuid CHARACTER VARYING(36) NOT NULL REFERENCES PRODUCT(uuid),
  category_uuid CHARACTER VARYING(36) NOT NULL REFERENCES CATEGORY(uuid)
);


