CREATE TABLE SOLR_SORTS(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  directionType CHARACTER VARYING(255) NOT NULL,
  solr_search_resolver_uuid CHARACTER VARYING(36) REFERENCES SOLR_SEARCH_RESOLVERS(uuid),
  solrField CHARACTER VARYING(255),
  solrFieldResolver CHARACTER VARYING(255)
);

CREATE UNIQUE INDEX SOLR_SORTS_UUID_IDX ON SOLR_SORTS(uuid);
CREATE UNIQUE INDEX SOLR_SORTS_CODE_IDX ON SOLR_SORTS(code);
CREATE INDEX SOLR_SORTS_NAME_IDX ON SOLR_SORTS(name);