CREATE TABLE FACETS(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  facetType CHARACTER VARYING(255) NOT NULL,
  forAllCategories BOOLEAN,
  feature_uuid CHARACTER VARYING(36) REFERENCES FEATURES(uuid),
  solr_index_field_uuid CHARACTER VARYING(36) REFERENCES SOLR_INDEX_FIELDS(uuid),
  solrCriteriaValueType CHARACTER VARYING(255) NOT NULL
);

CREATE UNIQUE INDEX FACETS_UUID_IDX ON FACETS(uuid);
CREATE UNIQUE INDEX FACETS_CODE_IDX ON FACETS(code);
CREATE INDEX  FACETS_NAME_IDX ON FACETS(name);

CREATE TABLE FACETS_CATEGORIES_LINKS(
  facet_uuid CHARACTER VARYING(36) NOT NULL REFERENCES FACETS(uuid),
  category_uuid CHARACTER VARYING(36) NOT NULL REFERENCES CATEGORIES(uuid)
);