CREATE TABLE FEATURE(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  catalog_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SHOP_CATALOG(uuid) ON DELETE RESTRICT,
  enumClass CHARACTER VARYING(255),
  featureType CHARACTER VARYING(255) NOT NULL
);

CREATE UNIQUE INDEX FEATURE_UUID_IDX ON FEATURE(uuid);
CREATE INDEX FEATURE_CODE_IDX ON FEATURE(code);
CREATE INDEX FEATURE_NAME_IDX ON FEATURE(name);


CREATE TABLE FEATURE_VALUE(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  catalog_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SHOP_CATALOG(uuid) ON DELETE RESTRICT,
  product_uuid CHARACTER VARYING(36) NOT NULL REFERENCES PRODUCT(uuid),
  feature_uuid CHARACTER VARYING(36) NOT NULL REFERENCES FEATURE(uuid),
  featureValue CHARACTER VARYING(255) NOT NULL,
  groupName CHARACTER VARYING(255) NOT NULL
);

CREATE UNIQUE INDEX FEATURE_VALUE_UUID_IDX ON FEATURE_VALUE(uuid);
CREATE INDEX FEATURE_VALUE_CODE_IDX ON FEATURE_VALUE(code);
CREATE INDEX FEATURE_VALUE_NAME_IDX ON FEATURE_VALUE(name);