CREATE TABLE SHOP_CATALOG(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX SHOP_CATALOG_UUID_IDX ON SHOP_CATALOG(uuid);
CREATE UNIQUE INDEX SHOP_CATALOG_CODE_IDX ON SHOP_CATALOG(code);
CREATE INDEX SHOP_CATALOG_NAME_IDX ON SHOP_CATALOG(name);

CREATE TABLE BIG_STRING (
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  catalog_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SHOP_CATALOG(uuid) ON DELETE RESTRICT,
  text_value TEXT NOT NULL
);

CREATE UNIQUE INDEX BIG_STRING_UUID_IDX ON BIG_STRING(uuid);
CREATE INDEX BIG_STRING_CODE_IDX ON BIG_STRING(code);
CREATE INDEX BIG_STRING_NAME_IDX ON BIG_STRING(name);

INSERT INTO SHOP_CATALOG(uuid, name, code, creationtime, modificationtime) VALUES (
  uuid_generate_v1(), 'Master catalog', 'master_catalog', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);