CREATE TABLE CURRENCIES(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  symbol CHARACTER VARYING(255) NOT NULL
);

INSERT INTO CURRENCIES(uuid, name, code, creationtime, modificationtime, symbol) VALUES (
  uuid_generate_v1(), 'Dollar USA', 'usd', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '$'
);

INSERT INTO CURRENCIES(uuid, name, code, creationtime, modificationtime, symbol) VALUES (
  uuid_generate_v1(), 'Euro', 'eur', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '€'
);

INSERT INTO CURRENCIES(uuid, name, code, creationtime, modificationtime, symbol) VALUES (
  uuid_generate_v1(), 'Russia ruble', 'rub', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'R'
);

CREATE UNIQUE INDEX CURRENCY_UUID_IDX ON CURRENCIES(uuid);
CREATE UNIQUE INDEX CURRENCY_CODE_IDX ON CURRENCIES(code);
CREATE INDEX CURRENCY_NAME_IDX ON CURRENCIES(name);

CREATE TABLE STORES(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  enabled BOOLEAN,
  default_currency_uuid CHARACTER VARYING(36) REFERENCES CURRENCIES(uuid)
);

CREATE TABLE STORES_CURRENCIES_LINKS(
  store_uuid CHARACTER VARYING(36) NOT NULL REFERENCES STORES(uuid),
  currency_uuid CHARACTER VARYING(36) NOT NULL REFERENCES CURRENCIES(uuid)
);

CREATE UNIQUE INDEX STORE_UUID_IDX ON STORES(uuid);
CREATE UNIQUE INDEX STORE_CODE_IDX ON STORES(code);
CREATE INDEX STORE_NAME_IDX ON STORES(name);

INSERT INTO STORES(uuid, name, code, creationtime, modificationtime, enabled) VALUES (
  uuid_generate_v1(), 'Default store', 'default_store', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE
);

CREATE TABLE WAREHOUSES(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  enabled BOOLEAN,
  store_uuid CHARACTER VARYING(36) NOT NULL REFERENCES STORES(uuid)
);

CREATE UNIQUE INDEX WAREHOUSE_UUID_IDX ON WAREHOUSES(uuid);
CREATE UNIQUE INDEX WAREHOUSE_CODE_IDX ON WAREHOUSES(code);
CREATE INDEX WAREHOUSE_NAME_IDX ON WAREHOUSES(name);
CREATE INDEX WAREHOUSE_STORE_UUID_IDX ON WAREHOUSES(store_uuid);

CREATE TABLE STOCKS(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  enabled BOOLEAN,
  product_count BIGINT NOT NULL,
  warehouse_uuid CHARACTER VARYING(36) NOT NULL REFERENCES WAREHOUSES(uuid),
  product_uuid CHARACTER VARYING(36) NOT NULL REFERENCES PRODUCTS(uuid),
  unit_uuid CHARACTER VARYING(36) NOT NULL REFERENCES UNITS(uuid)
);

CREATE UNIQUE INDEX STOCK_UUID_IDX ON STOCKS(uuid);
CREATE UNIQUE INDEX STOCK_CODE_IDX ON STOCKS(code);
CREATE INDEX STOCK_NAME_IDX ON STOCKS(name);
CREATE INDEX STOCK_WAREHOUSE_UUID_IDX ON STOCKS(warehouse_uuid);
CREATE INDEX STOCK_PRODUCT_UUID_IDX ON STOCKS(product_uuid);
