CREATE TABLE STORE(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  enabled BOOLEAN
);

CREATE UNIQUE INDEX STORE_UUID_IDX ON STORE(uuid);
CREATE UNIQUE INDEX STORE_CODE_IDX ON STORE(code);
CREATE INDEX STORE_NAME_IDX ON STORE(name);

INSERT INTO STORE(uuid, name, code, creationtime, modificationtime, enabled) VALUES (
  uuid_generate_v1(), 'Default store', 'default_store', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE
);

CREATE TABLE WAREHOUSE(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  enabled BOOLEAN,
  store_uuid CHARACTER VARYING(36) NOT NULL REFERENCES STORE(uuid)
);

CREATE UNIQUE INDEX WAREHOUSE_UUID_IDX ON WAREHOUSE(uuid);
CREATE UNIQUE INDEX WAREHOUSE_CODE_IDX ON WAREHOUSE(code);
CREATE INDEX WAREHOUSE_NAME_IDX ON WAREHOUSE(name);
CREATE INDEX WAREHOUSE_STORE_UUID_IDX ON WAREHOUSE(store_uuid);

CREATE TABLE STOCK(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  product_count BIGINT NOT NULL,
  warehouse_uuid CHARACTER VARYING(36) NOT NULL REFERENCES WAREHOUSE(uuid),
  product_uuid CHARACTER VARYING(36) NOT NULL REFERENCES PRODUCT(uuid),
  unit_uuid CHARACTER VARYING(36) NOT NULL REFERENCES UNIT(uuid)
);

CREATE UNIQUE INDEX STOCK_UUID_IDX ON STOCK(uuid);
CREATE UNIQUE INDEX STOCK_CODE_IDX ON STOCK(code);
CREATE INDEX STOCK_NAME_IDX ON STOCK(name);
CREATE INDEX STOCK_WAREHOUSE_UUID_IDX ON STOCK(warehouse_uuid);
CREATE INDEX STOCK_PRODUCT_UUID_IDX ON STOCK(product_uuid);
