CREATE TABLE SOLR_INDEX_TASK_PROPERTY(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  solrCollectionName CHARACTER VARYING(255) NOT NULL,
  query CHARACTER VARYING(2500) NOT NULL,
  indexEntityName CHARACTER VARYING(255) NOT NULL
);

CREATE UNIQUE INDEX INDEX_PROPERTY_UUID_IDX ON SOLR_INDEX_TASK_PROPERTY(uuid);
CREATE UNIQUE INDEX INDEX_PROPERTY_CODE_IDX ON SOLR_INDEX_TASK_PROPERTY(code);
CREATE INDEX  INDEX_PROPERTY_NAME_IDX ON SOLR_INDEX_TASK_PROPERTY(name);

CREATE TABLE SOLR_SEARCH_RESOLVER(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  solrCollectionName CHARACTER VARYING(255) NOT NULL,
  indexEntityName CHARACTER VARYING(255) NOT NULL,
  pageSize BIGINT NOT NULL
);

CREATE UNIQUE INDEX SOLR_SEARCH_RESOLVER_UUID_IDX ON SOLR_SEARCH_RESOLVER(uuid);
CREATE UNIQUE INDEX SOLR_SEARCH_RESOLVER_CODE_IDX ON SOLR_SEARCH_RESOLVER(code);
CREATE INDEX  SOLR_SEARCH_RESOLVER_NAME_IDX ON SOLR_SEARCH_RESOLVER(name);

CREATE TABLE SOLR_INDEX_FIELD(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  solrDocumentFieldName CHARACTER VARYING(255) NOT NULL,
  entityFieldName CHARACTER VARYING(2500) NOT NULL,
  solrFieldConverterBeanName CHARACTER VARYING(255),
  caseInsensitive BOOLEAN
);

CREATE UNIQUE INDEX SOLR_INDEX_FIELD_UUID_IDX ON SOLR_INDEX_FIELD(uuid);
CREATE UNIQUE INDEX SOLR_INDEX_FIELD_CODE_IDX ON SOLR_INDEX_FIELD(code);
CREATE INDEX  SOLR_INDEX_FIELD_NAME_IDX ON SOLR_INDEX_FIELD(name);

CREATE TABLE SOLR_INDEX_PROPERTIES_FIELDS_LINK(
  property_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SOLR_INDEX_TASK_PROPERTY(uuid),
  field_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SOLR_INDEX_FIELD(uuid)
);

CREATE TABLE SOLR_SEARCH_RESOLVERS_TEXT_FIELDS_LINK(
  resolver_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SOLR_SEARCH_RESOLVER(uuid),
  field_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SOLR_INDEX_FIELD(uuid)
);

CREATE TABLE TASKS(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  enabled BOOLEAN,
  status CHARACTER VARYING(255) NOT NULL,
  taskRunBeanName CHARACTER VARYING(255) NOT NULL,
  laststarttime TIMESTAMP,
  lastfinishtime TIMESTAMP,
  task_type CHARACTER VARYING(255) NOT NULL,
  solr_index_property_uuid CHARACTER VARYING(36) REFERENCES SOLR_INDEX_TASK_PROPERTY(uuid)
);

CREATE UNIQUE INDEX TASKS_UUID_IDX ON TASKS(uuid);
CREATE UNIQUE INDEX TASKS_CODE_IDX ON TASKS(code);
CREATE INDEX TASKS_NAME_IDX ON TASKS(name);
