CREATE TABLE SHOP_CATALOG(
  id BIGINT NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  entity_uid CHARACTER VARYING(36) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL
);

CREATE SEQUENCE SHOP_CATALOG_SEQ
  INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807
  START 1 CACHE 1;

