CREATE TABLE PRICE(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  catalog_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SHOP_CATALOG(uuid) ON DELETE RESTRICT,
  unit_uuid CHARACTER VARYING(36) REFERENCES UNIT(uuid) NOT NULL,
  product_uuid CHARACTER VARYING(36) REFERENCES PRODUCT(uuid) NOT NULL,
  currency_uuid CHARACTER VARYING(36) REFERENCES CURRENCY(uuid) NOT NULL,
  priceValue REAL NOT NULL
);

CREATE UNIQUE INDEX PRICE_UUID_IDX ON PRICE(uuid);
CREATE INDEX PRICE_CODE_IDX ON PRICE(code);
CREATE INDEX PRICE_NAME_IDX ON PRICE(name);