CREATE TABLE CATEGORY(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  catalog_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SHOP_CATALOG(uuid) ON DELETE RESTRICT,
  main_supercategory_uuid CHARACTER VARYING(36) REFERENCES CATEGORY(uuid) ON DELETE SET NULL,
  description_uuid CHARACTER VARYING(36) REFERENCES BIG_STRING(uuid) ON DELETE SET NULL
);

CREATE UNIQUE INDEX CATEGORY_UUID_IDX ON CATEGORY(uuid);
CREATE INDEX CATEGORY_CODE_IDX ON CATEGORY(code);
CREATE INDEX CATEGORY_NAME_IDX ON CATEGORY(name);

CREATE TABLE CATEGORIES_SUPERCATEGORIES_LINK(
  category_uuid CHARACTER VARYING(36) NOT NULL REFERENCES CATEGORY(uuid),
  supercategory_uuid CHARACTER VARYING(36) NOT NULL REFERENCES CATEGORY(uuid)
);