CREATE TABLE DICTIONARY_TYPES(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX DICTIONARY_TYPE_UUID_IDX ON DICTIONARY_TYPES(uuid);
CREATE UNIQUE INDEX DICTIONARY_TYPE_CODE_IDX ON DICTIONARY_TYPES(code);
CREATE INDEX  DICTIONARY_TYPE_NAME_IDX ON DICTIONARY_TYPES(name);

CREATE TABLE DICTIONARY_ITEMS(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL UNIQUE,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  dictionary_type_uuid CHARACTER VARYING(36) NOT NULL REFERENCES DICTIONARY_TYPES(uuid)
);

CREATE UNIQUE INDEX DICTIONARY_ITEM_UUID_IDX ON DICTIONARY_ITEMS(uuid);
CREATE UNIQUE INDEX DICTIONARY_ITEM_CODE_IDX ON DICTIONARY_ITEMS(code);
CREATE INDEX  DICTIONARY_ITEM_NAME_IDX ON DICTIONARY_ITEMS(name);
CREATE INDEX  DICTIONARY_ITEM_TYPE_IDX ON DICTIONARY_ITEMS(dictionary_type_uuid);

CREATE TABLE FEATURES(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  catalog_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SHOP_CATALOGS(uuid) ON DELETE RESTRICT,
  featureType CHARACTER VARYING(255) NOT NULL,
  dictionary_type_uuid CHARACTER VARYING(36) REFERENCES DICTIONARY_TYPES(uuid)
);

CREATE UNIQUE INDEX FEATURE_UUID_IDX ON FEATURES(uuid);
CREATE INDEX FEATURE_CODE_IDX ON FEATURES(code);
CREATE INDEX FEATURE_NAME_IDX ON FEATURES(name);


CREATE TABLE FEATURE_VALUES(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  catalog_uuid CHARACTER VARYING(36) NOT NULL REFERENCES SHOP_CATALOGS(uuid) ON DELETE RESTRICT,
  product_uuid CHARACTER VARYING(36) NOT NULL REFERENCES PRODUCTS(uuid),
  feature_uuid CHARACTER VARYING(36) NOT NULL REFERENCES FEATURES(uuid),
  featureValue CHARACTER VARYING(255) NOT NULL,
  groupName CHARACTER VARYING(255) NOT NULL
);

CREATE UNIQUE INDEX FEATURE_VALUE_UUID_IDX ON FEATURE_VALUES(uuid);
CREATE INDEX FEATURE_VALUE_CODE_IDX ON FEATURE_VALUES(code);
CREATE INDEX FEATURE_VALUE_NAME_IDX ON FEATURE_VALUES(name);
